---
abstract: 'perlcritic add-ons that generally check for dead code.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Test2::V0: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.041, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-TooMuchCode
provides:
  Perl::Critic::Policy::TooMuchCode::ProhibitDuplicateLiteral:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitDuplicateLiteral.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitDuplicateSub:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitDuplicateSub.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitExcessiveColons:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitExcessiveColons.pm
    version: '0.01'
  Perl::Critic::Policy::TooMuchCode::ProhibitExtraStricture:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitExtraStricture.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitLargeBlock:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitLargeBlock.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitLargeTryBlock:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitLargeTryBlock.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitUnnecessaryScalarKeyword:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitUnnecessaryScalarKeyword.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitUnnecessaryUTF8Pragma:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitUnnecessaryUTF8Pragma.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitUnusedConstant:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitUnusedConstant.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitUnusedImport:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitUnusedImport.pm
  Perl::Critic::Policy::TooMuchCode::ProhibitUnusedInclude:
    file: lib/Perl/Critic/Policy/TooMuchCode/ProhibitUnusedInclude.pm
  Perl::Critic::TooMuchCode:
    file: lib/Perl/Critic/TooMuchCode.pm
    version: '0.18'
requires:
  List::Util: '1.50'
  PPIx::QuoteLike: '0'
  PPIx::Utils: '0.002'
  Perl::Critic: '0'
  Scalar::Util: '1.50'
  version: '0.77'
resources:
  bugtracker: https://github.com/gugod/Perl-Critic-TooMuchCode/issues
  repository: https://github.com/gugod/Perl-Critic-TooMuchCode.git
version: '0.18'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: MIT
x_static_install: '1'
