version: 2
jobs:
  criticism:
    docker:
      - image: gugod/perlcritic:latest
    steps:
      - checkout
      - run: perlcritic --profile .perlcriticrc lib t
  test:
    docker:
      - image: perl:5.28
    steps:
      - checkout
      - run: perl -V
      - run: cpanm --notest --installdeps .
      - run: yath test --qvf
workflows:
  version: 2
  test_and_critic:
    jobs:
      - criticism
      - test
