## name less than 3 levels
## failures 0
## cut

if ($a) { print $a };

if ($a == 1) {
    if ($b == 1) {
        print 42;
    }
}

## name 3 Levels
## failures 0
## cut

if ($a) {
    if ($b) {
        if ($c) {
            print "$a $b $c";
        }
    }
}

## name 4 Levels
## failures 1
## cut

if ($b == 1) {
    if ($c == 1) {
        if ($d == 1) {
            if ($e) {
                print "Hadoken";
            }
        }
    }
}
