name: Installation Test

on:
  push:
    branches:
      - fun

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Install Authoring Dependencies
        run: cpanm -n App::ModuleBuildTiny && cpanm -q -n --no-man-pages --installdeps .
      - name: Generate dist
        run: |-
          mbtiny dist
          export DIST=*.tar.gz
          echo "::set-env name=DIST::$DIST"
      - name: Install in a perl:5.34 container (--notest)
        container: perl:5.34
        run: cpanm --notest $DIST
      - name: Install in a perl:5.34 container
        container: perl:5.34
        run: cpanm $DIST
